In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
print(a)
a[0]

[1 2 3]


1

In [8]:
import time
import sys

In [11]:
b = range(10000)
print(sys.getsizeof(5) * len(b))

280000


In [12]:
c = np.arange(10000)
print(c.size * c.itemsize)

40000


In [13]:
size = 100000

In [14]:
L1 = range(size)
L2 = range(size)

A1 = np.arange(size)
A2 = np.arange(size)

In [20]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print("Time is ", (time.time() - start) * 1000)

start1 = time.time()
result1 = A1 + A2
print(result1)
print("Time is ", (time.time() - start1) * 1000)

Time is  21.941423416137695
[     0      2      4 ... 199994 199996 199998]
Time is  0.9973049163818359


In [21]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a.ndim

2

In [23]:
a.itemsize

4

In [24]:
a.shape

(3, 2)

In [25]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])